// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqowomhiomozgrtfsjpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb3dvbWhpb21vemdydGZzanBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjkyMTcsImV4cCI6MjA1OTg0NTIxN30.Yx3YBV9GLewdfyw8RAfgQSsUK_0OtQO6vnJ4KAnLLD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);